version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    restart: 'always'
    environment:
      MYSQL_DATABASE: movies
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: myuser
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: 'movie-api'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movies
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: 1234
      BASE_URL: "http://localhost:8080"
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  mysql-data:
