version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    restart: 'always'
    environment:
      MYSQL_DATABASE: movies
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: myuser
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
